name: CMake

on: [push, pull_request]

jobs:

  skip_check:
    # This is to avoid duplicated jobs when working with PRs and branches,
    # and avoid builds when only README changes are made, but can be removed
    name: Skip Check
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          skip_after_successful_duplicate: 'false'
          paths_ignore: '["**.md"]'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: skip_check
    if: ${{ needs.skip_check.outputs.should_skip != 'true' }}

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake .

    - name: Build
      run: make

    - name: Test
      # Same than `make test'
      run: ctest
